[features]
seeds = false
skip-lint = false

[programs.localnet]
aleph_solana_contract = "ALepH1n9jxScbz45aZhBYVa35zxBNbKSvL6rWQpb4snc"
cpi_example = "83eRytbwtuAdVyakF6DVyMHtUxQRNKDjtped19pVJMSc"

[provider]
cluster = "localnet"
wallet = "/Users/riki/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
